from .company_views import *
from .permission_views import *
from .dashboard_views import *
from .main_views import *
from .number_distribution_views import *
from .OCR_views import *
from .register_sign_in_logout_views import *
from .twb2bmainitem_views import *
from .upload_views import *
from .twallowance_views import *
