# Generated by Django 5.1.7 on 2025-07-31 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0001_initial'),
    ]

    operations = [

    ]
