# Generated by Django 5.1.7 on 2025-03-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twa0101',
            name='invoice_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='twa0101',
            name='void_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
