# Generated by Django 5.1.5 on 2025-02-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapfagll03',
            name='document_number',
            field=models.CharField(max_length=20),
        ),
    ]
