# Generated by Django 5.1.7 on 2025-05-13 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twallowancelineitem',
            name='linked_invoice',
        ),
    ]
