# Generated by Django 5.1.7 on 2025-07-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0002_remove_twb2bmainitem_reject_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twb2bmainitem',
            name='reject_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitem',
            name='reject_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
