# Generated by Django 5.1.7 on 2025-04-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0002_remove_twallowance_company_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='sales_amount',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='sys_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
