# Generated by Django 5.1.5 on 2025-02-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0002_alter_sapfagll03_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapfagll03',
            name='document_number',
            field=models.IntegerField(),
        ),
    ]
