# Generated by Django 5.1.7 on 2025-05-13 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0002_remove_twallowancelineitem_linked_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='twallowancelineitem',
            name='linked_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allowance_lineitems', to='e_invoices.twb2bmainitem'),
        ),
    ]
