# Generated by Django 5.1.7 on 2025-03-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0002_twa0101_invoice_status_twa0101_void_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twa0101',
            name='invoice_status',
            field=models.CharField(blank=True, default='未開立', max_length=10, null=True),
        ),
    ]
