# Generated by Django 5.1.7 on 2025-04-09 01:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0002_alter_twa0101_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_id',
            field=models.CharField(default=2025, error_messages={'invalid': '請輸入10碼以內字元，僅限英文大小寫或數字'}, max_length=10, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{1,10}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='is_foreign_ecomm',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_identifier',
            field=models.CharField(error_messages={'invalid': '請輸入8碼數字'}, max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.IntegerField(choices=[(0, 'Headquarter'), (1, 'Branch')], default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_identifer',
            field=models.CharField(error_messages={'invalid': '請輸入9碼數字'}, max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$')]),
        ),
    ]
