# Generated by Django 5.1.7 on 2025-04-09 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0003_company_company_id_company_is_foreign_ecomm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_number', models.CharField(max_length=20)),
                ('end_number', models.CharField(max_length=20)),
                ('current_number', models.CharField(blank=True, max_length=20, null=True)),
                ('last_used_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('used', 'Used')], default='available', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_distributions', to='e_invoices.company')),
            ],
        ),
    ]
