# Generated by Django 5.1.7 on 2025-04-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0003_alter_twb2bmainitem_sales_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twb2bmainitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='twb2bmainitem',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='twb2bmainitem',
            name='donate_mark',
        ),
        migrations.RemoveField(
            model_name='twb2bmainitem',
            name='group_mark',
        ),
        migrations.RemoveField(
            model_name='twb2bmainitem',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='twb2bmainitem',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='twb2bmainitem',
            name='seller_name',
        ),
        migrations.RemoveField(
            model_name='twb2bmainitem',
            name='tax_identifier',
        ),
        migrations.RemoveField(
            model_name='twb2bmainitem',
            name='void_status',
        ),
        migrations.AddField(
            model_name='twb2blineitem',
            name='erp_number',
            field=models.CharField(default=2020, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twb2bmainitem',
            name='export_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twb2blineitem',
            name='line_tax_type',
            field=models.CharField(blank=True, choices=[(1, '應稅'), (2, '零稅率'), (3, '免稅')], max_length=1, null=True),
        ),
    ]
