# Generated by Django 5.1.7 on 2025-05-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0003_twallowancelineitem_linked_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twallowance',
            name='is_valid_amount',
        ),
        migrations.RemoveField(
            model_name='twallowance',
            name='is_valid_tax',
        ),
        migrations.AlterField(
            model_name='twallowance',
            name='allowance_amount',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='twallowance',
            name='allowance_status',
            field=models.CharField(blank=True, default='未開立', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='twallowance',
            name='allowance_tax',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
    ]
