# Generated by Django 5.1.6 on 2025-02-25 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0003_alter_sapfagll03_document_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twa0101',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=4)),
                ('job_type', models.CharField(max_length=4)),
                ('corporate_id', models.CharField(max_length=8)),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('invoice_date', models.DateField()),
                ('invoice_time', models.TimeField()),
                ('seller_name', models.CharField(max_length=225)),
                ('buyer_name', models.CharField(max_length=225)),
                ('buyer_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('main_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('customs_clearance_mark', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.CharField(blank=True, max_length=2, null=True)),
                ('invoice_type', models.CharField(max_length=50)),
                ('group_mark', models.CharField(blank=True, max_length=1, null=True)),
                ('donate_mark', models.CharField(max_length=10)),
                ('zero_tax_rate_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('reserved1', models.CharField(blank=True, max_length=20, null=True)),
                ('reserved2', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=7, max_digits=20)),
                ('unit', models.CharField(blank=True, max_length=6, null=True)),
                ('unit_price', models.DecimalField(decimal_places=7, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=7, max_digits=20)),
                ('sequence_number', models.CharField(max_length=4)),
                ('remark', models.CharField(blank=True, max_length=120, null=True)),
                ('relate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('sales_amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('tax_type', models.CharField(max_length=50)),
                ('tax_rate', models.CharField(max_length=50)),
                ('tax_amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('original_currency_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=13, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amount_details', to='e_invoices.invoice')),
            ],
        ),
    ]
