# Generated by Django 5.1.7 on 2025-03-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0003_alter_twa0101_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twa0101',
            name='id',
        ),
        migrations.AlterField(
            model_name='twa0101',
            name='invoice_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
