# Generated by Django 5.1.7 on 2025-07-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0003_twb2bmainitem_reject_date_twb2bmainitem_reject_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='reject_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
