# Generated by Django 5.1.6 on 2025-02-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0004_twa0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twa0101',
            name='invoice',
        ),
    ]
