# Generated by Django 5.1.7 on 2025-05-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0004_remove_twallowance_is_valid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twb2bmainitem',
            name='allowance_status',
            field=models.CharField(blank=True, default='未開立折讓單', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitem',
            name='invoice_allowance_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitem',
            name='invoice_allowance_tax',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
    ]
