# Generated by Django 5.1.7 on 2025-04-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0004_remove_twb2bmainitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twallowance',
            name='allowance_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twallowance',
            name='export_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='buyer_remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
