# Generated by Django 5.1.7 on 2025-04-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0004_numberdistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberdistribution',
            name='initial_char',
            field=models.CharField(default=2025, max_length=4),
            preserve_default=False,
        ),
    ]
