# Generated by Django 5.1.7 on 2025-08-04 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0004_alter_twb2bmainitem_reject_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companynotificationconfig',
            old_name='output_dir_E0501',
            new_name='input_dir_E0501',
        ),
        migrations.RenameField(
            model_name='companynotificationconfig',
            old_name='output_dir_E0502',
            new_name='input_dir_E0502',
        ),
        migrations.RenameField(
            model_name='companynotificationconfig',
            old_name='output_dir_E0503',
            new_name='input_dir_E0503',
        ),
        migrations.RenameField(
            model_name='companynotificationconfig',
            old_name='output_dir_ProcessResult',
            new_name='input_dir_ProcessResult',
        ),
    ]
