# Generated by Django 5.1.7 on 2025-04-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0005_numberdistribution_initial_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberdistribution',
            name='period',
            field=models.CharField(default=2025, max_length=5),
            preserve_default=False,
        ),
    ]
