# Generated by Django 5.1.7 on 2025-05-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0005_twb2bmainitem_allowance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twallowancelineitem',
            name='invoice_cancel_status',
            field=models.CharField(blank=True, choices=[('0', '未作廢'), ('1', '已作廢')], max_length=20, null=True),
        ),
    ]
