# Generated by Django 5.1.7 on 2025-08-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0005_rename_output_dir_e0501_companynotificationconfig_input_dir_e0501_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twb2blineitemine',
            old_name='twb2bmainitem',
            new_name='twb2bmainitemine',
        ),
        migrations.RenameField(
            model_name='twb2blineitemins',
            old_name='twb2bmainitem',
            new_name='twb2bmainitemins',
        ),
        migrations.AddField(
            model_name='twb2bmainitemine',
            name='reject_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitemine',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitemine',
            name='reject_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitemins',
            name='reject_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitemins',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitemins',
            name='reject_remark',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitemins',
            name='reject_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
