# Generated by Django 5.1.7 on 2025-08-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0006_rename_twb2bmainitem_twb2blineitemine_twb2bmainitemine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twb2bmainitemine',
            name='reject_remark',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
