# Generated by Django 5.1.7 on 2025-04-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0006_alter_twallowance_allowance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twallowance',
            name='allowance_amount',
            field=models.DecimalField(decimal_places=7, default=2000, max_digits=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='twallowance',
            name='allowance_status',
            field=models.CharField(default='未開立', max_length=6),
        ),
        migrations.AlterField(
            model_name='twallowance',
            name='allowance_tax',
            field=models.DecimalField(decimal_places=0, default=2000, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='twallowance',
            name='erp_number',
            field=models.CharField(default=2000, max_length=20),
            preserve_default=False,
        ),
    ]
