# Generated by Django 5.1.7 on 2025-05-20 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0006_twallowancelineitem_invoice_cancel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twallowancelineitem',
            old_name='invoice_cancel_status',
            new_name='line_invoice_cancel_status',
        ),
    ]
