# Generated by Django 5.1.7 on 2025-04-11 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0006_numberdistribution_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='twa0101',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='twa0101_invoices', to='e_invoices.company'),
            preserve_default=False,
        ),
    ]
