# Generated by Django 5.1.7 on 2025-04-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0007_twa0101_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberdistribution',
            name='current_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='numberdistribution',
            name='end_number',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='numberdistribution',
            name='start_number',
            field=models.CharField(max_length=8),
        ),
    ]
