# Generated by Django 5.1.7 on 2025-08-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0007_twb2bmainitemine_reject_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twb2bmainitemins',
            old_name='buyer_identifier',
            new_name='buyer_id',
        ),
        migrations.RenameField(
            model_name='twb2bmainitemins',
            old_name='company_identifier',
            new_name='seller_id',
        ),
        migrations.RemoveField(
            model_name='twb2bmainitemins',
            name='NPOBAN',
        ),
        migrations.AddField(
            model_name='twb2bmainitemine',
            name='group_mark',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitemins',
            name='carrier_id1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitemins',
            name='carrier_id2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitemins',
            name='carrier_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitemins',
            name='group_mark',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitemins',
            name='npoban',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
