# Generated by Django 5.1.7 on 2025-04-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0007_alter_twallowance_allowance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twallowancelineitem',
            name='line_allowance_amount',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='twallowancelineitem',
            name='line_allowance_tax',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='twallowancelineitem',
            name='line_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='twallowancelineitem',
            name='line_quantity',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='twallowancelineitem',
            name='line_tax_type',
            field=models.CharField(blank=True, choices=[('1', '應稅'), ('2', '零稅率'), ('3', '免稅')], max_length=1, null=True),
        ),
    ]
