# Generated by Django 5.1.7 on 2025-06-02 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0007_rename_invoice_cancel_status_twallowancelineitem_line_invoice_cancel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twallowance',
            name='allowance_cancel_reason',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='不能包含以下特殊符號：< > ` " &', regex='^[^<>"`&]+$')]),
        ),
        migrations.AlterField(
            model_name='twallowance',
            name='allowance_cancel_remark',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='不能包含以下特殊符號：< > ` " &', regex='^[^<>"`&]+$')]),
        ),
        migrations.AlterField(
            model_name='twallowance',
            name='creator_remark',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='不能包含以下特殊符號：< > ` " &', regex='^[^<>"`&]+$')]),
        ),
        migrations.AlterField(
            model_name='twallowancelineitem',
            name='line_description',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.RegexValidator(message='不能包含以下特殊符號：< > ` " &', regex='^[^<>"`&]+$')]),
        ),
        migrations.AlterField(
            model_name='twb2blineitem',
            name='erp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='twb2blineitem',
            name='line_description',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.RegexValidator(message='不能包含以下特殊符號：< > ` " &', regex='^[^<>"`&]+$')]),
        ),
        migrations.AlterField(
            model_name='twb2blineitem',
            name='line_remark',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='不能包含以下特殊符號：< > ` " &', regex='^[^<>"`&]+$')]),
        ),
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='不能包含以下特殊符號：< > ` " &', regex='^[^<>"`&]+$')]),
        ),
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='cancel_remark',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='不能包含以下特殊符號：< > ` " &', regex='^[^<>"`&]+$')]),
        ),
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='creator_remark',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='不能包含以下特殊符號：< > ` " &', regex='^[^<>"`&]+$')]),
        ),
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='reserved1',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='不能包含以下特殊符號：< > ` " &', regex='^[^<>"`&]+$')]),
        ),
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='reserved2',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='不能包含以下特殊符號：< > ` " &', regex='^[^<>"`&]+$')]),
        ),
    ]
