# Generated by Django 5.1.7 on 2025-08-05 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0008_rename_buyer_identifier_twb2bmainitemins_buyer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twb2bmainitemins',
            old_name='npoban',
            new_name='npobaN',
        ),
    ]
