# Generated by Django 5.1.7 on 2025-06-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0008_alter_twallowance_allowance_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twb2blineitem',
            name='line_tax_type',
            field=models.CharField(blank=True, choices=[('1', '應稅'), ('2', '零稅率'), ('3', '免稅')], max_length=1, null=True),
        ),
    ]
