# Generated by Django 5.1.7 on 2025-04-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0008_alter_twallowancelineitem_line_allowance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twallowancelineitem',
            name='line_sequence_number',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='twallowancelineitem',
            name='line_unit_price',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=13, null=True),
        ),
    ]
