# Generated by Django 5.1.7 on 2025-04-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0008_alter_numberdistribution_current_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberdistribution',
            name='initial_char',
            field=models.CharField(max_length=2),
        ),
    ]
