# Generated by Django 5.1.7 on 2025-04-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0009_alter_twallowancelineitem_line_sequence_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twallowancelineitem',
            name='line_allowance_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='twallowancelineitem',
            name='line_allowance_tax',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='twallowancelineitem',
            name='line_quantity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='twallowancelineitem',
            name='line_unit',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='twallowancelineitem',
            name='line_unit_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
    ]
