# Generated by Django 5.1.7 on 2025-08-05 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0009_rename_npoban_twb2bmainitemins_npoban'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twb2bmainitemins',
            old_name='npobaN',
            new_name='npoban',
        ),
    ]
