# Generated by Django 5.1.7 on 2025-06-04 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0009_alter_twb2blineitem_line_tax_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twb2bmainitem',
            old_name='mof_respone',
            new_name='mof_response',
        ),
    ]
