# Generated by Django 5.1.7 on 2025-04-14 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0009_alter_numberdistribution_initial_char'),
    ]

    operations = [
        migrations.CreateModel(
            name='TWB2BMainItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b2b_b2C', models.CharField(max_length=3)),
                ('sys_number', models.CharField(max_length=20)),
                ('invoice_number', models.CharField(blank=True, max_length=10, null=True)),
                ('invoice_date', models.CharField(max_length=8)),
                ('invoice_time', models.TimeField(blank=True, null=True)),
                ('invoice_date_time', models.CharField(blank=True, max_length=8, null=True)),
                ('invoice_period', models.CharField(max_length=5)),
                ('ERP_number', models.CharField(max_length=10)),
                ('ERP_year', models.CharField(max_length=4)),
                ('ERP_date', models.CharField(max_length=8)),
                ('ERP_reference', models.CharField(blank=True, max_length=60, null=True)),
                ('seller_tax_id', models.CharField(max_length=10)),
                ('seller_bp_id', models.CharField(blank=True, max_length=20, null=True)),
                ('seller_name', models.CharField(max_length=60)),
                ('buyer_tax_id', models.CharField(max_length=10)),
                ('buyer_name', models.CharField(max_length=60)),
                ('buyer_bp_id', models.CharField(blank=True, max_length=20, null=True)),
                ('buyer_remark', models.CharField(blank=True, max_length=1, null=True)),
                ('main_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('customs_clearance_mark', models.CharField(blank=True, max_length=1, null=True)),
                ('category', models.CharField(blank=True, max_length=2, null=True)),
                ('relate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_type', models.CharField(max_length=2)),
                ('bonded_area_confirm', models.CharField(blank=True, max_length=1, null=True)),
                ('zero_tax_rate_reason', models.CharField(blank=True, max_length=2, null=True)),
                ('reserved1', models.CharField(blank=True, max_length=20, null=True)),
                ('reserved2', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_amount', models.DecimalField(decimal_places=7, max_digits=13)),
                ('freetax_sales_amount', models.DecimalField(decimal_places=7, max_digits=13)),
                ('zerotax_sales_amount', models.DecimalField(decimal_places=7, max_digits=13)),
                ('tax_type', models.CharField(blank=True, choices=[(1, '應稅'), (2, '零稅率'), (3, '免稅')], max_length=1, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_tax_amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=7, max_digits=13)),
                ('original_currency_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=13, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=120, null=True)),
                ('tax_type_main', models.CharField(blank=True, choices=[(1, '應稅'), (2, '零稅率'), (3, '免稅')], max_length=1, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=13, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=10, null=True)),
                ('invoice_status', models.CharField(blank=True, max_length=10, null=True)),
                ('void_status', models.CharField(blank=True, max_length=10, null=True)),
                ('mof_date', models.DateField(blank=True, null=True)),
                ('mof_respone', models.CharField(blank=True, max_length=200, null=True)),
                ('mof_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('creator', models.CharField(blank=True, max_length=10, null=True)),
                ('creator_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twb2bmainitem_invoices', to='e_invoices.company')),
            ],
        ),
        migrations.CreateModel(
            name='TWB2BLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_description', models.CharField(max_length=500)),
                ('line_quantity', models.CharField(max_length=50)),
                ('line_unit', models.CharField(blank=True, max_length=6, null=True)),
                ('line_unit_price', models.DecimalField(decimal_places=7, max_digits=20)),
                ('line_amount', models.DecimalField(decimal_places=7, max_digits=20)),
                ('line_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('line_sequence_number', models.CharField(max_length=4)),
                ('line_relate_number', models.CharField(max_length=4)),
                ('twb2bmainitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='e_invoices.twb2bmainitem')),
            ],
        ),
    ]
