# Generated by Django 5.1.7 on 2025-04-14 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0010_twb2bmainitem_twb2blineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberdistribution',
            name='start_number',
            field=models.CharField(error_messages={'invalid': '請輸入8碼數字'}, max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$')]),
        ),
    ]
