# Generated by Django 5.1.7 on 2025-06-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0010_rename_mof_respone_twb2bmainitem_mof_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='export_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
