# Generated by Django 5.1.7 on 2025-04-14 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0011_alter_numberdistribution_start_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twa0101',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twa0101_invoices', to='e_invoices.company'),
        ),
    ]
