# Generated by Django 5.1.7 on 2025-06-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0011_alter_twb2bmainitem_export_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='twb2bmainitem',
            name='NPOBAN',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
