# Generated by Django 5.1.7 on 2025-04-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0012_alter_twa0101_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twa0101',
            old_name='company',
            new_name='company_id',
        ),
    ]
