# Generated by Django 5.1.7 on 2025-06-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0012_twb2bmainitem_npoban'),
    ]

    operations = [
        migrations.AddField(
            model_name='twb2bmainitem',
            name='donate_mark',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
