# Generated by Django 5.1.7 on 2025-06-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0013_twb2bmainitem_donate_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='twb2bmainitem',
            name='print_mark',
            field=models.CharField(blank=True, choices=[('Y', '是'), ('N', '否')], max_length=1, null=True),
        ),
    ]
