# Generated by Django 5.1.7 on 2025-04-14 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0013_rename_company_twa0101_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twa0101',
            name='company_id',
        ),
        migrations.AddField(
            model_name='twa0101',
            name='company',
            field=models.ForeignKey(default=2022, on_delete=django.db.models.deletion.CASCADE, related_name='twa0101_invoices', to='e_invoices.company'),
            preserve_default=False,
        ),
    ]
