# Generated by Django 5.1.7 on 2025-04-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0014_remove_twa0101_company_id_twa0101_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberdistribution',
            name='start_number',
            field=models.CharField(max_length=8),
        ),
    ]
