# Generated by Django 5.1.7 on 2025-06-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0014_twb2bmainitem_print_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='twb2bmainitem',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=13, null=True),
        ),
    ]
