# Generated by Django 5.1.7 on 2025-06-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0015_twb2bmainitem_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='twb2bmainitem',
            name='random_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
