# Generated by Django 5.1.7 on 2025-04-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0015_alter_numberdistribution_start_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twb2bmainitem',
            name='seller_tax_id',
        ),
        migrations.AddField(
            model_name='twb2blineitem',
            name='line_sales_amount',
            field=models.DecimalField(decimal_places=7, default=2022, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twb2blineitem',
            name='line_tax_amount',
            field=models.DecimalField(decimal_places=7, default=2020, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twb2blineitem',
            name='line_tax_type',
            field=models.CharField(blank=True, choices=[(1, '應稅'), (2, '零稅率'), (3, '免稅')], max_length=1, null=True),
        ),
    ]
