# Generated by Django 5.1.7 on 2025-04-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0016_remove_twb2bmainitem_seller_tax_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twb2bmainitem',
            name='donate_mark',
            field=models.CharField(default=2020, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twb2bmainitem',
            name='group_mark',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
