# Generated by Django 5.1.7 on 2025-06-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0016_twb2bmainitem_random_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='twb2bmainitem',
            name='buyer_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
