# Generated by Django 5.1.7 on 2025-07-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0017_twb2bmainitem_buyer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberdistribution',
            name='inovice_type',
            field=models.CharField(default=7, max_length=2),
            preserve_default=False,
        ),
    ]
