# Generated by Django 5.1.7 on 2025-04-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0017_twb2bmainitem_donate_mark_twb2bmainitem_group_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='b2b_b2C',
            field=models.CharField(max_length=10),
        ),
    ]
