# Generated by Django 5.1.7 on 2025-04-14 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0018_alter_twb2bmainitem_b2b_b2c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twb2bmainitem',
            old_name='b2b_b2C',
            new_name='b2b_b2c',
        ),
    ]
