# Generated by Django 5.1.7 on 2025-07-02 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0018_numberdistribution_inovice_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numberdistribution',
            old_name='inovice_type',
            new_name='invoice_type',
        ),
    ]
