# Generated by Django 5.1.7 on 2025-07-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0019_rename_inovice_type_numberdistribution_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='twb2bmainitem',
            name='void_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitem',
            name='void_reason',
            field=models.CharField(blank=True, default='註銷', max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitem',
            name='void_remark',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitem',
            name='void_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
