# Generated by Django 5.1.7 on 2025-04-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0019_rename_b2b_b2c_twb2bmainitem_b2b_b2c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='invoice_time',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
