# Generated by Django 5.1.7 on 2025-07-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0020_twb2bmainitem_void_date_twb2bmainitem_void_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='void_reason',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
