# Generated by Django 5.1.7 on 2025-07-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0021_alter_twb2bmainitem_void_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twallowance',
            old_name='mof_respone',
            new_name='mof_response',
        ),
    ]
