# Generated by Django 5.1.7 on 2025-04-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0021_alter_twb2bmainitem_freetax_sales_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=13, null=True),
        ),
    ]
