# Generated by Django 5.1.7 on 2025-07-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0022_rename_mof_respone_twallowance_mof_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twallowance',
            name='allowance_amount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='twallowance',
            name='allowance_tax',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='twallowancelineitem',
            name='line_allowance_amount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='twallowancelineitem',
            name='line_allowance_tax',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True),
        ),
    ]
