# Generated by Django 5.1.7 on 2025-07-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0023_alter_twallowance_allowance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twb2blineitem',
            name='line_tax_amount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='accurated_allowance_amount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='freetax_sales_amount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='original_currency_amount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='remaining_allowance_amount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='sales_amount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='zerotax_sales_amount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=13, null=True),
        ),
    ]
