# Generated by Django 5.1.7 on 2025-04-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0023_alter_twb2blineitem_line_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='ERP_date',
            field=models.DateField(max_length=8),
        ),
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='invoice_date',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='invoice_date_time',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
    ]
