# Generated by Django 5.1.7 on 2025-04-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0024_alter_twb2bmainitem_erp_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twb2blineitem',
            name='line_tax_type',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
