# Generated by Django 5.1.7 on 2025-07-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0024_alter_twb2blineitem_line_tax_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twb2blineitem',
            name='line_unit_price',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True),
        ),
    ]
