# Generated by Django 5.1.7 on 2025-07-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0025_alter_twb2blineitem_line_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twb2bmainitem',
            old_name='cancel_mof_respone',
            new_name='cancel_mof_response',
        ),
    ]
