# Generated by Django 5.1.7 on 2025-04-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0025_alter_twb2blineitem_line_tax_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twb2bmainitem',
            old_name='company',
            new_name='company_id',
        ),
    ]
