# Generated by Django 5.1.7 on 2025-04-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0026_rename_company_twb2bmainitem_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twb2bmainitem',
            old_name='ERP_reference',
            new_name='company_identifier',
        ),
        migrations.RenameField(
            model_name='twb2bmainitem',
            old_name='ERP_date',
            new_name='erp_date',
        ),
        migrations.RenameField(
            model_name='twb2bmainitem',
            old_name='ERP_number',
            new_name='erp_number',
        ),
        migrations.RemoveField(
            model_name='twb2bmainitem',
            name='ERP_year',
        ),
        migrations.RemoveField(
            model_name='twb2bmainitem',
            name='invoice_date_time',
        ),
        migrations.RemoveField(
            model_name='twb2bmainitem',
            name='tax_type_main',
        ),
        migrations.AddField(
            model_name='twb2bmainitem',
            name='erp_reference',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitem',
            name='tax_identifier',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='b2b_b2c',
            field=models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C')], max_length=3),
        ),
    ]
