# Generated by Django 5.1.7 on 2025-04-15 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0027_rename_erp_reference_twb2bmainitem_company_identifier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twb2bmainitem',
            old_name='buyer_tax_id',
            new_name='buyer_identifier',
        ),
        migrations.AddField(
            model_name='twb2bmainitem',
            name='sys_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TWAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b2b_b2c', models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C')], max_length=3)),
                ('sys_number', models.CharField(max_length=20)),
                ('sys_date', models.DateTimeField(blank=True, null=True)),
                ('allowance_number', models.CharField(blank=True, max_length=16, null=True)),
                ('allowance_date', models.DateField(blank=True, null=True)),
                ('allowance_period', models.CharField(blank=True, max_length=5, null=True)),
                ('allowance_type', models.CharField(blank=True, default='02', max_length=2, null=True)),
                ('erp_number', models.CharField(max_length=20)),
                ('erp_date', models.DateTimeField()),
                ('erp_reference', models.CharField(blank=True, max_length=60, null=True)),
                ('seller_bp_id', models.CharField(blank=True, max_length=20, null=True)),
                ('buyer_Identifier', models.CharField(max_length=10)),
                ('buyer_name', models.CharField(blank=True, max_length=60, null=True)),
                ('buyer_bp_id', models.CharField(blank=True, max_length=20, null=True)),
                ('line_sequence_number', models.CharField(max_length=4)),
                ('line_original_invoice_date', models.DateField(blank=True, null=True)),
                ('line_original_invoice_number', models.CharField(blank=True, max_length=10, null=True)),
                ('line_description', models.CharField(max_length=500)),
                ('line_quantity', models.DecimalField(decimal_places=7, max_digits=13)),
                ('line_unit', models.CharField(blank=True, max_length=6, null=True)),
                ('line_unit_price', models.DecimalField(decimal_places=7, max_digits=13)),
                ('line_tax_type', models.CharField(choices=[('1', '應稅'), ('2', '零稅率'), ('3', '免稅')], max_length=1)),
                ('line_allowance_amount', models.DecimalField(decimal_places=7, max_digits=13)),
                ('line_allowance_tax', models.DecimalField(decimal_places=0, max_digits=20)),
                ('allowance_amount', models.DecimalField(decimal_places=7, max_digits=13)),
                ('allowance_tax', models.DecimalField(decimal_places=0, max_digits=20)),
                ('allowance_status', models.CharField(default='未開立', max_length=6)),
                ('mof_date', models.DateField(blank=True, null=True)),
                ('mof_respone', models.CharField(blank=True, max_length=200, null=True)),
                ('mof_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('creator', models.CharField(blank=True, max_length=10, null=True)),
                ('creator_remark', models.CharField(blank=True, max_length=200, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twallowance', to='e_invoices.company')),
            ],
        ),
    ]
