# Generated by Django 5.1.7 on 2025-04-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0028_rename_buyer_tax_id_twb2bmainitem_buyer_identifier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twb2bmainitem',
            old_name='company_id',
            new_name='company',
        ),
    ]
