# Generated by Django 5.1.7 on 2025-04-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0029_rename_company_id_twb2bmainitem_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='twb2bmainitem',
            name='company_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
