# Generated by Django 5.1.7 on 2025-04-16 09:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0030_twb2bmainitem_company_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twb2bmainitem',
            name='company_code',
        ),
        migrations.AddField(
            model_name='twb2bmainitem',
            name='cancel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitem',
            name='cancel_mof_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitem',
            name='cancel_mof_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitem',
            name='cancel_mof_respone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitem',
            name='cancel_period',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitem',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitem',
            name='cancel_remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitem',
            name='cancel_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitem',
            name='returntax_document_number',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(error_messages={'invalid': '請輸入10碼以內字元，僅限英文大小寫或數字'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='company',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='twb2bmainitem_invoices', to='e_invoices.company', to_field='company_id'),
        ),
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('未開立', '未開立'), ('已開立', '已開立'), ('已作廢', '已作廢')], default='未開立', max_length=20, null=True),
        ),
    ]
