# Generated by Django 5.1.7 on 2025-04-16 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0031_remove_twb2bmainitem_company_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twb2bmainitem',
            old_name='company',
            new_name='company_id',
        ),
    ]
