# Generated by Django 5.1.7 on 2025-04-16 09:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0032_rename_company_twb2bmainitem_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twallowance',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='twb2bmainitem',
            name='company_id',
        ),
        migrations.AddField(
            model_name='twallowance',
            name='allowance_cancel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twallowance',
            name='allowance_cancel_reason',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='twallowance',
            name='allowance_cancel_remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='twallowance',
            name='allowance_cancel_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twallowance',
            name='cancel_mof_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twallowance',
            name='cancel_mof_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='twallowance',
            name='cancel_mof_respone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='twb2bmainitem',
            name='company',
            field=models.ForeignKey(default=2025, on_delete=django.db.models.deletion.CASCADE, related_name='twb2bmainitem_invoices', to='e_invoices.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twb2bmainitem',
            name='company_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(error_messages={'invalid': '請輸入10碼以內字元，僅限英文大小寫或數字'}, max_length=10, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='invoice_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
