# Generated by Django 5.1.7 on 2025-04-17 02:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0033_rename_company_id_twallowance_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='apply_eGUI',
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^.+@.+$', message='請輸入100碼以內含有「@」符號的電子郵件地址')]),
        ),
        migrations.AddField(
            model_name='company',
            name='reporting_period',
            field=models.IntegerField(choices=[(1, '單月'), (2, '雙月')], default=2),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_identifier',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', message='請輸入8碼數字')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_register_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.IntegerField(choices=[(0, '總機構'), (1, '分支機構')], default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='head_company_identifer',
            field=models.ForeignKey(blank=True, limit_choices_to={'company_type': 0}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='e_invoices.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_identifer',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', message='請輸入9碼數字')]),
        ),
    ]
