# Generated by Django 5.1.7 on 2025-04-21 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0034_remove_company_apply_egui_company_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Myinvoiceportal',
        ),
        migrations.DeleteModel(
            name='Sapfagll03',
        ),
        migrations.AddField(
            model_name='twallowance',
            name='company_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(error_messages={'invalid': '請輸入10碼以內字元，僅限英文大小寫或數字'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='tax_type',
            field=models.CharField(blank=True, choices=[('1', '應稅'), ('2', '零稅率'), ('3', '免稅')], max_length=1, null=True),
        ),
    ]
