# Generated by Django 5.1.7 on 2025-04-22 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0035_delete_invoice_delete_myinvoiceportal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twallowance',
            name='company_code',
        ),
        migrations.RemoveField(
            model_name='twallowance',
            name='line_allowance_amount',
        ),
        migrations.RemoveField(
            model_name='twallowance',
            name='line_allowance_tax',
        ),
        migrations.RemoveField(
            model_name='twallowance',
            name='line_description',
        ),
        migrations.RemoveField(
            model_name='twallowance',
            name='line_original_invoice_date',
        ),
        migrations.RemoveField(
            model_name='twallowance',
            name='line_original_invoice_number',
        ),
        migrations.RemoveField(
            model_name='twallowance',
            name='line_quantity',
        ),
        migrations.RemoveField(
            model_name='twallowance',
            name='line_sequence_number',
        ),
        migrations.RemoveField(
            model_name='twallowance',
            name='line_tax_type',
        ),
        migrations.RemoveField(
            model_name='twallowance',
            name='line_unit',
        ),
        migrations.RemoveField(
            model_name='twallowance',
            name='line_unit_price',
        ),
        migrations.CreateModel(
            name='TWAllowanceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_sequence_number', models.CharField(max_length=4)),
                ('line_original_invoice_date', models.DateField(blank=True, null=True)),
                ('line_original_invoice_number', models.CharField(blank=True, max_length=10, null=True)),
                ('line_description', models.CharField(max_length=500)),
                ('line_quantity', models.DecimalField(decimal_places=7, max_digits=13)),
                ('line_unit', models.CharField(blank=True, max_length=6, null=True)),
                ('line_unit_price', models.DecimalField(decimal_places=7, max_digits=13)),
                ('line_tax_type', models.CharField(choices=[('1', '應稅'), ('2', '零稅率'), ('3', '免稅')], max_length=1)),
                ('line_allowance_amount', models.DecimalField(decimal_places=7, max_digits=13)),
                ('line_allowance_tax', models.DecimalField(decimal_places=0, max_digits=20)),
                ('twb2bmainitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='e_invoices.twallowance')),
            ],
        ),
    ]
