# Generated by Django 5.1.7 on 2025-04-22 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0036_remove_twallowance_company_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twallowancelineitem',
            old_name='twb2bmainitem',
            new_name='twallowance',
        ),
    ]
