# Generated by Django 5.1.7 on 2025-04-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0037_rename_twb2bmainitem_twallowancelineitem_twallowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='twallowance',
            name='company_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
