# Generated by Django 5.1.7 on 2025-04-22 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0038_twallowance_company_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twallowance',
            old_name='buyer_Identifier',
            new_name='buyer_identifier',
        ),
    ]
