# Generated by Django 5.1.7 on 2025-04-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0039_rename_buyer_identifier_twallowance_buyer_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twb2blineitem',
            name='line_sales_amount',
        ),
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='invoice_status',
            field=models.CharField(blank=True, default='未開立', max_length=10, null=True),
        ),
    ]
