# Generated by Django 5.1.7 on 2025-04-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0040_remove_twb2blineitem_line_sales_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twb2bmainitem',
            name='donate_mark',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
