# Generated by Django 5.1.7 on 2025-04-22 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0041_alter_twb2bmainitem_donate_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='twallowancelineitem',
            name='linked_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_invoices.twb2bmainitem'),
        ),
    ]
