# Generated by Django 5.1.7 on 2025-04-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0042_twallowancelineitem_linked_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='twallowance',
            name='total_invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=13, null=True),
        ),
    ]
