# Generated by Django 5.1.7 on 2025-04-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0043_twallowance_total_invoice_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twallowance',
            old_name='total_invoice_amount',
            new_name='invoice_total_amount',
        ),
    ]
