# Generated by Django 5.1.7 on 2025-04-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoices', '0044_rename_total_invoice_amount_twallowance_invoice_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twallowance',
            name='invoice_total_amount',
        ),
    ]
